services:
  clinic-app:
    env_file:
      - /home/.env
    environment:
      NODE_ENV: production  # 线上环境
    volumes:
      - ./clinic-app/dist:/usr/src/app/dist
    restart: always  # 保证服务异常退出后自动重启

  mysql-container:
    volumes:
      - /data/mysql:/var/lib/mysql  # 线上 MySQL 数据持久化路径

  redis-container:
    volumes:
      - /data/redis:/data  # 线上 Redis 数据持久化路径