services:
  clinic-app:
    build:
      context: ./clinic-app/
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: ${NODE_ENV}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    networks:
      - clinic-network

  mysql-container:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - clinic-network

  redis-container:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - clinic-network

networks:
  clinic-network:
    external: true