services:
  clinic-app:
    env_file:
      - /home/.env
    environment:
      NODE_ENV: production  # 线上环境
    restart: always  # 保证服务异常退出后自动重启

  mysql-container:
    volumes:
      - /data/mysql:/var/lib/mysql  # 线上 MySQL 数据持久化路径

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/clinic-backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 挂载配置文件
      - /data/nginx-key:/etc/letsencrypt  # 证书存放目录
    depends_on:
      - app-network
    networks:
      - clinic-network  # 这里手动加入网络


  redis-container:
    volumes:
      - /data/redis:/data  # 线上 Redis 数据持久化路径

networks:
  app-network:
    external: true
